#!/bin/sh
BCPATH=/home/$USER/BraineCode
START=$(pwd)
touch $BCPATH/gits.list

python3 /home/$USER/.bin/binhelpers/subdirfind.py $BCPATH .git

while read line; do
  # echo $line
  cd $line
  git pull
done < $BCPATH/gits.list

cd $START
